### ISSUE TITLE
[feat] Add instrumentations to opentelemetry registry page

### ISSUE THREAD

**Issue by BobDu** [uptrace/opentelemetry-go-extra#100]
This repository provides many good instrumentations for Go.
But I spent a lot of time trying to find it.
Why not add this instrumentations to opentelemetry registry page to help another people easy find it?
https://opentelemetry.io/ecosystem/registry/adding

**Comment by vmihailenco** [comment]
I've sent https://github.com/open-telemetry/opentelemetry.io/pull/2673, https://github.com/open-telemetry/opentelemetry.io/pull/2672, https://github.com/open-telemetry/opentelemetry.io/pull/2671
