### ISSUE TITLE
otelsql does not work with pgx driver

### ISSUE THREAD

**Issue by oshurubura** [uptrace/opentelemetry-go-extra#34]
pgx driver overrides CheckNamedValue to empty which cause driver to fail from working.

The otelsql should call connection `NamedValueChecker` if there is such available.

If not, return ErrSkip.

Here's the fix https://github.com/oshurubura/opentelemetry-go-extra/commit/73d420c07429c6ebd18effe6551844345eece864 and I'd love to create PR, but could you please let me know what else is required for this PR to be accepted and merged into main trunk?

**Comment by vmihailenco** [comment]
Hey @oshurubura ,

I've implemented a slightly different version in https://github.com/uptrace/opentelemetry-go-extra/pull/35 and added you as a co-author. Thanks for the reporting this issue.

**Comment by oshurubura** [comment]
Thanks for such a prompt fix 👍

**Comment by vmihailenco** [comment]
You are welcome
