### ISSUE TITLE
Caller lost when using `*otelzap.{Info|Warn|Debug}Context` methods

### ISSUE THREAD

**Issue by andremedeiros** [uptrace/opentelemetry-go-extra#40]
I was hoping I'd be able to use the `{Info|Warn|Debug}Context` methods instead of calling `Ctx(ctx)` to avoid allocations. This mostly works, but the caller gets lost with the former.

Code (`logger` is an instance of `*otelzap.Logger`):

```go
logger.Ctx(ctx).Info("Hello")
logger.InfoContext(ctx, "Hello")
```

Output:

```
{"level":"info","ts":1647377604.4693089,"caller":"foreman/main.go:18","msg":"Hello"}
{"level":"info","ts":1647377604.469389,"caller":"otelzap@v0.1.9/otelzap.go:111","msg":"Hello"}
```

Is this the expected behaviour?

**Comment by vmihailenco** [comment]
Thanks for the report - should be fixed.
