### ISSUE TITLE
how about export  patchDB() in otelsql/driver.go  ,I need call this function 

### ISSUE THREAD

**Issue by jixiuf** [uptrace/opentelemetry-go-extra#45]
https://github.com/uptrace/opentelemetry-go-extra/blob/main/otelsql/driver.go#L22

**Comment by vmihailenco** [comment]
Can you use `otelsql.Open` instead? `patchDB` creates a new db anyway.

**Comment by jixiuf** [comment]
thanks ,`otelsql.Open` is ok for me after double check.
