### ISSUE TITLE
WithTraceIDField(true) Does not write trace_id in the log 

### ISSUE THREAD

**Issue by hanyue2020** [uptrace/opentelemetry-go-extra#47]
In the Readme .it say otelzap.WithTraceIDField(true) configures the logger to add trace_id field to structured log messages

but actually it does not.

```
func (s SugaredLoggerWithCtx) Debugw(msg string, keysAndValues ...interface{}) {
	s.s.logKVs(s.ctx, zap.DebugLevel, msg, keysAndValues)
	s.s.skipCaller.Debugw(msg, keysAndValues...)
}
```
I found in logKVs function,it change keysAndValues,and return, but outside,the code does not use the return value ,so that's why there is no trace-id in the log file

**Comment by vmihailenco** [comment]
Try configuring `WithMinLevel` or using `Errorw` instead of `Debugw`.

**Comment by hanyue2020** [comment]
I have set that,but  it not works well. 
so I trace the code ,I found out 
```
func (s SugaredLoggerWithCtx) Debugw(msg string, keysAndValues ...interface{}) {
	s.s.logKVs(s.ctx, zap.DebugLevel, msg, keysAndValues)
	s.s.skipCaller.Debugw(msg, keysAndValues...)
}
``
it change keysAndValues content in the logKVs function and return ,but skipCaller.Debugw does't use the return value, it use the old keysAndValues. So even I  config WithMinLevel ,it does not work

**Comment by tmc** [comment]
I ran into the same here, FWIW.

**Comment by vmihailenco** [comment]
@hanyue2020 thanks for debugging this - I've sent https://github.com/uptrace/opentelemetry-go-extra/pull/58
