### ISSUE TITLE
otelgorm query limitation

### ISSUE THREAD

**Issue by ChasakisD** [uptrace/opentelemetry-go-extra#49]
Sometimes the SQL queries are huge and above 4k characters. It should be nice to create an option to limit the SQL query on the trace. I also opened a PR to resolve this issue. The idea is that if we want to limit the query to lets say 400 chars, we keep the first 200 chars and the last 200 chars of the query.

**Comment by igrayson** [comment]
(this is resolved by the `WithQueryFormatter` otelgorm config option added in the PR linked above)
