### ISSUE TITLE
`skipCaller` is not copied when calling `With` and `Ctx` on SugaredLogger - results in panic

### ISSUE THREAD

**Issue by piotrklosowski** [uptrace/opentelemetry-go-extra#62]
When first calling `With` function on SugaredLogger and then `Ctx`, any further occurring logging function calls result in panic as they require `skipCaller` to be not nil. `skipCaller` is not copied/updated when calling `With` function. Please confirm if it is a bug 

 Relevant code link below:
https://github.com/uptrace/opentelemetry-go-extra/blob/c155edf518eead3aeda618810078f543e3f1eca9/otelzap/otelzap.go#L379

**Comment by vmihailenco** [comment]
Yes, looks like a bug. Could you send a fix?
