### ISSUE TITLE
`SugaredLogger` is missing `DebugwContext` function

### ISSUE THREAD

**Issue by piotrklosowski** [uptrace/opentelemetry-go-extra#63]
As in the title `SugaredLogger` is missing `DebugwContext` function. On the other hand, `DebugfContext` is present.

**Comment by vmihailenco** [comment]
That is an overlook. There is `InfowContext`, but no `DebugwContext`. Could you create a PR?

**Comment by piotrklosowski** [comment]
Please see PR: https://github.com/uptrace/opentelemetry-go-extra/pull/64
