### ISSUE TITLE
Unable to silence logs for otelgorm

### ISSUE THREAD

**Issue by jlcrow** [uptrace/opentelemetry-go-extra#70]
github.com/uptrace/opentelemetry-go-extra/otelgorm v0.1.15

I've tried silencing the log output multiple ways, including setting the standard OTEL_LOG_LEVEL env to "error", setting the gorm logger to Silent and setting WithoutMetrics on otelgorm.

```
       db, err := gorm.Open(postgres.Open(conf.GetString("mydb")), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})

	if err != nil {
		panic("Unable to connect to database")
	}

	// init gorm otel plugin to use global provider
	otelgormOptions := []otelgorm.Option{
		otelgorm.WithTracerProvider(otel.GetTracerProvider()),
		otelgorm.WithDBName(conf.GetString("mydb")),
		otelgorm.WithoutMetrics(),
	}
	if err := db.Use(otelgorm.NewPlugin(otelgormOptions...)); err != nil {
		panic(err)
      } 
```
Interested in capturing traces, but don't want the timings written to the logs, currently every traced call writes to the console out.

> categories 8.432288ms
> images 24.594036ms
> video 25.112542ms
> itemData 27.238386ms
> call duration  27.259222ms
> getItemData response time:  27.524261ms
> topSellerBadge 83.17909ms {}
> shippingItemInventory 87.832197ms
> itemSkus 88.931746ms
> department 91.833751ms
> itemPositions 93.313601ms
> inventory 93.725081ms
> shippableDepartments 93.76177ms
> prices 94.200838ms
> itemStores 94.882105ms
> shippingItemStore 99.481928ms
> getItemLocationData response time:  101.97452ms
> ItemPositionBadge response time:  106.724171ms

**Comment by vmihailenco** [comment]
Do those logs disappear when you remove `db.Use(otelgorm.NewPlugin(otelgormOptions...))`? otelgorm should not print anything...
