### ISSUE TITLE
otelsql doesn't pass the label attributes when reporting db stats

### ISSUE THREAD

**Issue by scott20315** [uptrace/opentelemetry-go-extra#87]
I suspect the attributes provided to `OpenDB` are being dropped inside `sqlOpenDB` when setting up `db.Stats` reporting via `ReportDBStatsMetrics`.
```
func sqlOpenDB(connector driver.Connector, instrum *dbInstrum) *sql.DB {
	db := sql.OpenDB(connector)
	ReportDBStatsMetrics(db, WithMeterProvider(instrum.meterProvider))
	return db
}
```
should probably look something like this
```
func sqlOpenDB(connector driver.Connector, instrum *dbInstrum) *sql.DB {
	db := sql.OpenDB(connector)
	ReportDBStatsMetrics(db, WithMeterProvider(instrum.meterProvider), WithAttributes(instrum.attrs))
	return db
}
```
I'm not seeing the `db.system` label on any of the `db.Stats` metrics but it is still present as expected on the `query.timing` metric that comes from the tracing collection.

My current workaround is to direct register the `db.Stats` collection with `ReportDBStatsMetrics` but that doesn't disable the automatic collection started by `OpenDB`.

**Comment by vmihailenco** [comment]
@scott20315 looks reasonable. Could you try to prepare a PR?

**Comment by scott20315** [comment]
https://github.com/uptrace/opentelemetry-go-extra/pull/88

**Comment by scott20315** [comment]
https://github.com/uptrace/opentelemetry-go-extra/pull/89
