### ISSUE TITLE
Breaking change?

### ISSUE THREAD

**Issue by jmarkleyrepay** [uptrace/opentelemetry-go-extra#96]
Hello, not sure if this a known issue, or if I am doing something incorrect.

I ran: `go get github.com/uptrace/opentelemetry-go-extra/otelgorm `

I get this error:

```
github.com/uptrace/opentelemetry-go-extra/otelgorm imports
        github.com/uptrace/opentelemetry-go-extra/otelsql imports
        go.opentelemetry.io/otel/metric/instrument/syncint64: cannot find module providing package go.opentelemetry.io/otel/metric/instrument/syncint64
```

Looking at the recent PR: https://github.com/uptrace/opentelemetry-go-extra/pull/95 - I see there is many changes to dependencies. Was this dependency just removed? go.opentelemetry.io/otel/metric/instrument/syncint64: cannot find module providing package go.opentelemetry.io/otel/metric/instrument/syncint64

**Comment by vmihailenco** [comment]
Should be fixed by v0.1.21
